x-common:
  image: &maven-jdk-image maven:3.9-eclipse-temurin-17
services:
  build:
    image: *maven-jdk-image
    command: mvn clean dependency:go-offline package install -U -DskipTests -Dgpg.skip=true -T 2.0C -B
    working_dir: /aws-maven
    environment:
      AWS_DEFAULT_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_PROFILE: dev/vault
      AWS_REGION: us-west-2
      GPG_PASSPHRASE: ${GPG_PASSPHRASE}
      GPG_SECRET_KEY: ${GPG_SECRET_KEY}
    volumes:
      - .:/aws-maven/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/

  test:
    image: *maven-jdk-image
    command: mvn verify -Dgpg.skip=true
    working_dir: /aws-maven
    environment:
      AWS_DEFAULT_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_PROFILE: dev/vault
      AWS_REGION: us-west-2
      GPG_PASSPHRASE: ${GPG_PASSPHRASE}
      GPG_SECRET_KEY: ${GPG_SECRET_KEY}
    volumes:
      - .:/aws-maven/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/