services:
  build:
    image: 190066226418.dkr.ecr.us-east-1.amazonaws.com/base/jvm11:20240413-f5906f03
    command: mvn clean dependency:go-offline package install -U -Dmaven.test.skip.exec -T 2.0C -B
    working_dir: ~/aws-maven
    environment:
      AWS_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    volumes:
      - .:/aws-maven/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/

  build-jdk-11:
    image: 190066226418.dkr.ecr.us-east-1.amazonaws.com/base/jvm11:20240413-f5906f03
    command: mvn clean dependency:go-offline package install -U -Dmaven.test.skip.exec -T 2.0C -B
    working_dir: ~/aws-maven
    environment:
      AWS_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    volumes:
      - .:/aws-maven/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/

  test:
    image: 190066226418.dkr.ecr.us-east-1.amazonaws.com/base/jvm11:20240413-f5906f03
    command: mvn verify
    working_dir: ~/aws-maven
    environment:
      AWS_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    volumes:
      - .:/aws-maven/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/